/**
 * Canonical technology labels for the admin project form (checkbox multiselect).
 * Matches common spellings used on the site / seeds / techStackIcons where possible.
 */

exports.TECHNOLOGY_OPTIONS = [
  '.NET',
  'ASP.NET Core',
  'Angular',
  'Ansible',
  'Apache Kafka',
  'Astro',
  'AWS',
  'Azure',
  'Bash',
  'Bootstrap',
  'CircleCI',
  'Cosmos DB',
  'C#',
  'Dart',
  'DigitalOcean',
  'Django',
  'Docker',
  'DynamoDB',
  'Elasticsearch',
  'Electron',
  'Express',
  'FastAPI',
  'Fastify',
  'Firebase',
  'Firebase Firestore',
  'Flutter',
  'Flask',
  'GCP',
  'GitHub Actions',
  'GitLab CI',
  'Go',
  'Google Cloud',
  'Google Maps API',
  'GraphQL',
  'gRPC',
  'Gin',
  'Git',
  'HL7 FHIR',
  'Heroku',
  'HTML/CSS',
  'Java',
  'JavaScript',
  'Jenkins',
  'JWT',
  'jQuery',
  'Kotlin',
  'Kubernetes',
  'Laravel',
  'MariaDB',
  'Material UI',
  'Microservices',
  'MongoDB',
  'MySQL',
  'NestJS',
  'Next.js',
  'nginx',
  'Node.js',
  'Nuxt',
  'OAuth',
  'OpenAI API',
  'PostgreSQL',
  'Python',
  'RabbitMQ',
  'React',
  'React Native',
  'Redis',
  'Redux',
  'Remix',
  'REST API',
  'Ruby',
  'Ruby on Rails',
  'Rust',
  'Sass',
  'Socket.io',
  'SolidJS',
  'Spring Boot',
  'SQLite',
  'Stripe',
  'Supabase',
  'Svelte',
  'SvelteKit',
  'Swift',
  'SwiftUI',
  'Tailwind CSS',
  'Terraform',
  'TypeORM',
  'TypeScript',
  'Vite',
  'Vue.js',
  'WebRTC',
  'WebSocket',
  'webpack',
  'Zustand'
].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }));
